apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunk-processor-deployment
  labels:
    app: chunk-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chunk-processor
  template:
    metadata:
      labels:
        app: chunk-processor
    spec:
      containers:
      - name: chunk-processor
        image: chunk-processor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5