apiVersion: v1
kind: Service
metadata:
  name: chunk-processor-service
  labels:
    app: chunk-processor
spec:
  selector:
    app: chunk-processor
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 5000  
  type: NodePort  